In [1]:
import torch
if torch.cuda.is_available():
    torch.device('cuda')
    device = 'cuda'
else:
    torch.device('cpu')
    device = 'cpu'

In [2]:
from ultralytics import YOLO
import cv2
import numpy as np
import os

# Загрузка модели YOLOv8
model = YOLO('./model/v7_best.pt').to(device)

In [3]:
sTmp =r'test_images/1_002301_zoom.JPG' # 1_002301_zoom_result # 1_002301_zoom # 1_002301_zoom
sTmpResult =r'c:\Utilits\StudyCV\LizaAlert\datasetWinter\valid\images\1_002301_zoom_result.JPG'

In [4]:
#results = model(["image1.jpg", "image2.jpg"])  # return a list of Results objects
results = model(img)  # return a list of Results objects

# Process results list
for result in results:
    boxes = result.boxes  # Boxes object for bounding box outputs
    masks = result.masks  # Masks object for segmentation masks outputs
    keypoints = result.keypoints  # Keypoints object for pose outputs
    probs = result.probs  # Probs object for classification outputs
    obb = result.obb  # Oriented boxes object for OBB outputs
    result.show()  # display to screen

NameError: name 'img' is not defined

In [52]:
results[0].boxes.conf.numpy()[0]

np.float32(0.52994794)

In [29]:
for s in boxes.xywh:
    print(s)

tensor([6820.4453, 2427.4995,  128.6255,   83.8584])
tensor([5390.8105,  919.9011,   98.0059,  109.2949])
tensor([ 439.5468, 4942.5264,   97.3505,   69.9443])


In [30]:
boxes.xywh

tensor([[6820.4453, 2427.4995,  128.6255,   83.8584],
        [5390.8105,  919.9011,   98.0059,  109.2949],
        [ 439.5468, 4942.5264,   97.3505,   69.9443]])

In [17]:
boxes.conf

tensor([0.5299])

In [4]:
from src.solution import predict, predict_multiple

import cv2 
# r'test_images/1_002301_zoom.JPG' # 1_002301_zoom_result # 1_002301_zoom # 1_002301_zoom
img = cv2.imread(r'test_images/1_002301_zoom.JPG')
img1 = cv2.imread(r'test_images/1_000178.JPG')

In [5]:
import json
image_as_list = img.tolist()

# Save the list to a JSON file
with open('example_predict.json', 'w') as json_file:
    json.dump({"image_1": image_as_list}, json_file)

In [8]:
with open('example_predict.json', 'r') as json_file:
    a = json.load(json_file)

In [13]:
type(img)

numpy.ndarray

In [10]:
np.array(image_as_list).shape

(1415, 2020, 3)

In [7]:
predict_multiple([img])

(1415, 2020, 3)

0: 448x640 1 body, 379.7ms
Speed: 9.5ms preprocess, 379.7ms inference, 0.4ms postprocess per image at shape (1, 3, 448, 640)


[[{'xc': np.float32(1170.883),
   'yc': np.float32(642.1708),
   'w': np.float32(74.6974),
   'h': np.float32(60.0264),
   'label': np.float32(0.0),
   'score': np.float32(0.5299)}]]

In [6]:
img.shape

(1415, 2020, 3)

In [7]:
results = model(img)  # return a list of Results objects
res = results[0].boxes

# Process results list
for i in range(len(res)):
    boxes = res[i].xywh  # Boxes object for bounding box outputs


0: 448x640 1 body, 366.3ms
Speed: 1.9ms preprocess, 366.3ms inference, 0.4ms postprocess per image at shape (1, 3, 448, 640)


In [10]:
boxes

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0.])
conf: tensor([0.5299])
data: tensor([[1.1335e+03, 6.1216e+02, 1.2082e+03, 6.7218e+02, 5.2995e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1415, 2020)
shape: torch.Size([1, 6])
xywh: tensor([[1170.8831,  642.1708,   74.6974,   60.0264]])
xywhn: tensor([[0.5796, 0.4538, 0.0370, 0.0424]])
xyxy: tensor([[1133.5344,  612.1576, 1208.2318,  672.1840]])
xyxyn: tensor([[0.5612, 0.4326, 0.5981, 0.4750]])

In [80]:
results[0].boxes#.numpy()#[0]

ultralytics.engine.results.Boxes object with attributes:

cls: tensor([0.])
conf: tensor([0.5299])
data: tensor([[1.1335e+03, 6.1216e+02, 1.2082e+03, 6.7218e+02, 5.2995e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: (1415, 2020)
shape: torch.Size([1, 6])
xywh: tensor([[1170.8831,  642.1708,   74.6974,   60.0264]])
xywhn: tensor([[0.5796, 0.4538, 0.0370, 0.0424]])
xyxy: tensor([[1133.5344,  612.1576, 1208.2318,  672.1840]])
xyxyn: tensor([[0.5612, 0.4326, 0.5981, 0.4750]])